# Generated by Django 3.0.6 on 2020-06-09 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vdt_design', '0002_auto_20200529_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pid',
            fields=[
                ('sname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pidtype', models.CharField(choices=[('PID', 'PID'), ('ATO', 'ATO')], default='PID', max_length=3)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('cogs', models.FloatField(default=0)),
                ('gpl', models.FloatField()),
                ('discount', models.FloatField(default=0.7)),
                ('netprice', models.FloatField(blank=True)),
                ('power_typ', models.FloatField()),
                ('power_max', models.FloatField()),
                ('mtbf', models.FloatField(default=1000000000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
